export type ApuracaoPonto = {
  almocoLivre?: boolean;
  apenasAtraso?: number;
  apenasAtrasoDiurno?: number;
  apenasAtrasoNoturno?: number;
  arquivado?: boolean;
  atrasoEntrada?: number;
  bancoMaisCredDebNegativo?: number;
  bancoMaisCredDebPositivo?: number;
  colorAlert?: 'danger' | 'info';
  colunaMix1?: number;
  colunaMix2?: number;
  colunaMix3?: number;
  colunaMix4?: number;
  compensado?: boolean;
  date?: string;
  dateTimeInicio?: string;
  dateTimeStr?: string;
  descontoDsr?: number;
  descontoDsrInteiro?: number;
  diaFechamento?: number;
  diasTrabalhados?: number;
  diasUteis?: number;
  dsrConsideradoMinutos?: number;
  error?: string | null;
  extraAdicionadaDiurna?: number;
  extraAdicionadaNoturna?: number;
  extraAdicionadaNoturna_MultiplicadoNot?: number;
  extraDiurna?: number;
  extraDiurna_MultiplicadoEx?: number;
  extraEntrada?: number;
  extraInterjornada?: number;
  extraInterjornada_MultiplicadoEx?: number;
  extraNoturna?: number;
  extraNoturna_MultiplicadoEx?: number;
  extraNoturna_MultiplicadoExNot?: number;
  extraNoturna_MultiplicadoNot?: number;
  faltaDiaInteiro?: boolean;
  faltasDiasInteiro?: number;
  folga?: boolean;
  holiday?: string | null;
  horaExtraDeCadaPercentual?: number[];
  horaExtraDeCadaPercentual_MultiplicadoEx?: number[];
  horaExtraDeCadaPercentual_MultiplicadoExNot?: number[];
  horaExtraDeCadaPercentual_MultiplicadoNot?: number[];
  horarioFechamento?: string;
  horasApenasFalta?: number;
  horasAusentes?: number;
  horasDiurnasNaoExtra?: number;
  horasExtraIntervalo?: number;
  horasExtrasCalculadas?: number;
  horasExtrasCalculadas_MultiplicadoEx?: number;
  horasExtrasCalculadas_MultiplicadoExNot?: number;
  horasExtrasCalculadas_MultiplicadoNot?: number;
  horasFaltaAtraso?: number;
  horasNoturnasNaoExtra?: number;
  horasNoturnasNaoExtra_MultiplicadoNot?: number;
  horasTotalNaoExtra?: number;
  horasTotalNaoExtra_MultiplicadoNot?: number;
  horasTotalNoturno?: number;
  horasTotalNoturno_MultiplicadoNot?: number;
  horasUteis?: number;
  iconAlert?: 'fa fa-times' | 'fa fa-info';
  idAfdChangeAlmoco?: number | null;
  idAfdChangeCompensacao?: number | null;
  idAfdChangeFolga?: number | null;
  idAfdChangeNeutro?: number | null;
  idHorarioContratual?: number;
  idJustification?: number | null;
  idPerson?: number;
  idShift?: number;
  idx?: number;
  isHoliday?: number;
  listAcjefOverwriteExtraIndex?: number | null;
  listAcjefOverwriteStr?: string[];
  listAfdtExcluidos?: any[];
  listAfdtManutencao?: AfdtManutencao[];
  minutosAbono?: number;
  minutosAjuste?: number;
  minutosFolga?: number;
  name?: string;
  neutro?: boolean;
  paginas?: number;
  percentuaisExtra?: number[];
  pis?: number;
  possuiPendencias?: boolean;
  pulouAlmoco?: number;
  saidaAntecipada?: number;
  saldoBancoAjustado?: number;
  saldoBancoAjustadoMaisCredDeb?: number;
  saldoBancoCredDeb?: number;
  saldoBancoFinalDia?: number;
  sobreaviso?: number;
  sobreavisoSaldo?: number;
  sobreavisoTrabalhado?: number;
  strHorarioContratualSimples?: string;
  toolTipAlert?: string;
  totalHorasTrabalhadas?: number;
};

export type AfdtManutencao = {
  typeClassification?: string | null;
  typeEntradaSaida?: string | null;
  typeRegister?: string | null;
  abreviationJustification?: string | null;
  afdChange?: string | null;
  afdtLogs?: any[];
  date?: string;
  dateInsertedStr?: string;
  dateTime?: string;
  dateTimeStr?: string;
  deslocamento?: number;
  deslocamentoDia?: number;
  diferencaConsiderada?: number;
  diferencaReal?: number;
  hora?: number;
  horaPrevista?: number;
  idAfd?: number | null;
  idAfdChange?: number | null;
  idJustification?: number | null;
  idPerson?: number;
  idx?: number;
  isTemporary?: boolean;
  nameOperator?: string | null;
  oculto?: boolean;
  pis?: string;
  reason?: string;
};

export type UserLogs = {
  id?: number | null;
  nome?: string | null;
  matricula?: string | null;
  apuracaoPonto?: ApuracaoPonto[];
};
